import React from "react";
import Head from "next/head";
import Sidebar from "../components/Sidebar";
import Modal from "../components/Modal";
import { useRouter } from "next/router";

import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
} from "@firebase/firestore";
import { getProviders, getSession, useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import { useRecoilState } from "recoil";
import { modalState } from "../atoms/modalAtom";
import Post from "../components/Post";
import Login from "../components/Login";
import { db } from "../firebase";
import {ArrowLeftIcon } from "@heroicons/react/outline";
import Comment from "../components/Comment";
import Widgets from "../components/Widgets";

const PostPage = ({ trendingResults, followResults, providers }) => {
  const { data: session } = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState);
  const [post, setPost] = useState();
  const [comments, setComments] = useState([])
  const router = useRouter();
  const { id } = router.query;

  useEffect(
    () =>
      onSnapshot(doc(db, "posts", id), (snapshot) => {
        setPost(snapshot.data());
      }),
    [db]
  );

  useEffect(
    () =>
      onSnapshot(
        query(
          collection(db, "posts", id, "comments"),
          orderBy("timestamp", "desc")
        ),
        (snapshot) => setComments(snapshot.docs)
      ),
    [db, id]
  );

  if (!session) return <Login providers={providers} />;

  return (
    <div className="">
      <Head>
        <title>
          {post?.username} on Twitter: {post?.text}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar />

        <div
          className="flex-grow border-l border-r border-gray-700 
        max-w-2xl sm:ml:[73px] xl:ml-[370px]
        "
        >
          <div
            className="flex item-center px-1.5 py-2 
             text-[#d9d9d9] font-semibold
            text-xl gap-x-4 sticky top-0 z-50 backdrop-blur-xl
            "
          >
            <div
              className="hoverAnimation w-9 h-9 flex justify-center items-center xl:px-0"
              onClick={() => router.push("/")}
            >
              <ArrowLeftIcon className="h-5 text-white" />
            </div>
            Tweet
          </div>

          <Post id={id} post={post} postPage />

          {comments.length > 0 && (
            <div className="pb-72">
                {comments.map(comment => (
                    <Comment key={comment.id} 
                    id = {comment.id}
                    comment={comment.data()} />
                ))}
            </div>
          )}
        </div>

        <Widgets 
        />

        {isOpen && <Modal />}
      </main>
    </div>
  );
};

export default PostPage;

export async function getServerSideProps(context) {

  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
    
      providers,
      session,
    },
  };
}
